name: Build LibreELEC-master-arm

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build All"]
    type:
      - complete

jobs:
  pre_build:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v4
        with:
          concurrent_skipping: 'always'

  build:
    needs: pre_build
    if: ${{ needs.pre_build.outputs.should_skip != 'true' }}

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare build
        run: |
          rm -f LibreELEC.tv/target/*

      - name: Restore sources cache
        run: |
          if [ -d ../build-cache/sources ]; then 
            rm -f sources  
            ln -s ../build-cache/sources sources
          fi

      - name: Build LibreELEC-master-arm
        run: |
          ./build.sh -config LibreELEC-master-arm -extra easyvdr

      - name: Save sources cache
        run: |
          mkdir -p ../build-cache
          
          if [ ! -d ../build-cache/sources ]; then
            mv sources ../build-cache/sources
          else
            rm sources
          fi

      - name: Copy build artifacts
        run: |
          mv LibreELEC.tv/target/*tar ../build-artifacts/LibreELEC-master-arm 
          mv LibreELEC.tv/target/*tar.shs256 ../build-artifacts/LibreELEC-master-arm

      - name: Create index file
        run: |
          ~/.local/bin/create_index
