name: Build CoreELEC-19

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build All"]
    type:
      - complete

jobs:
  pre_build:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v4
        with:
          concurrent_skipping: 'always'

  build:
    needs: pre_build
    if: ${{ needs.pre_build.outputs.should_skip != 'true' }}

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare build
        run: |
          mkdir -p image-artifacts
          rm -f image-artifacts/*

      - name: Restore sources cache
        run: |
          if [ -d ../build-cache/sources ]; then 
            rm -f sources  
            ln -s ../build-cache/sources sources
          fi

      - name: Build coreelec-19-VDR
        run: |
          ./build.sh -config CoreELEC-19 -extra easyvdr

      - name: Save sources cache
        run: |
          mkdir -p ../build-cache
          
          if [ ! -d ../build-cache/sources ]; then
            mv sources ../build-cache/sources
          else
            rm sources
          fi
