name: Cron Build VDRSternELEC

on:
  workflow_dispatch:
  # schedule:
  #  - cron: '0 23 * * 3'

jobs:
  # This workflow is configured to run only in repository 'Zabrimus/VDRSternELEC'
  # If you also want to run this workflow, then change or remove the condition in job 'cron'

  cron:
    if: github.repository == 'Zabrimus/VDRSternELEC'
    uses: ./.github/workflows/build.yml
