name: Cron Build VDRSternELEC

on:
  workflow_dispatch:
  schedule:
    - cron: '10 0 * * 4'

jobs:
  # This workflow is configured to run only in repository 'Zabrimus/VDRSternELEC'
  # If you also want to run this workflow, then change or remove the condition in job 'cron'

  buildtype:
    runs-on: ubuntu-20.04
    outputs:
      type: ${{ steps.get.outputs.type }}

    steps:
      - name: Get type of build
        id: get
        run: |
          if [ $(date +"%d") -lt 7 ]; then
              echo "type=full" >> "$GITHUB_OUTPUT"
          else
              echo "type=tar" >> "$GITHUB_OUTPUT"
          fi

  cron_tar:
    needs: buildType
    if: ${{ github.repository == 'Zabrimus/VDRSternELEC' && needs.buildType.outputs.type == 'tar' }}
    uses: ./.github/workflows/build.yml
    with:
      target: "all default"
      defaulttarget: "CoreELEC-20-ng CoreELEC-21-ng CoreELEC-22-no LibreELEC-13-aarch64-AMLGX LibreELEC-13-aarch64-Allwinner-H6 LibreELEC-13-aarch64-Rockchip-RK3399 LibreELEC-13-aarch64-RPi-RPi4 LibreELEC-13-aarch64-RPi-RPi5 LibreELEC-12-aarch64-AMLGX LibreELEC-12-aarch64-Allwinner-H6 LibreELEC-12-aarch64-Rockchip-RK3399 LibreELEC-12-aarch64-RPi-RPi4 LibreELEC-12-aarch64-RPi-RPi5"
      addons: "dvb-latest"
      extras: "easyvdr,channellogos,remotetranscode,cefbrowser"
      extraparameter: "-releaseonly"
    secrets: inherit

  cron_full:
    needs: buildType
    if: ${{ github.repository == 'Zabrimus/VDRSternELEC' && needs.buildType.outputs.type == 'full' }}
    uses: ./.github/workflows/build.yml
    with:
      target: "all default"
      defaulttarget: "CoreELEC-20-ng CoreELEC-21-ng CoreELEC-22-no LibreELEC-13-aarch64-AMLGX LibreELEC-13-aarch64-Allwinner-H6 LibreELEC-13-aarch64-Rockchip-RK3399 LibreELEC-13-aarch64-RPi-RPi4 LibreELEC-13-aarch64-RPi-RPi5 LibreELEC-12-aarch64-AMLGX LibreELEC-12-aarch64-Allwinner-H6 LibreELEC-12-aarch64-Rockchip-RK3399 LibreELEC-12-aarch64-RPi-RPi4 LibreELEC-12-aarch64-RPi-RPi5"
      addons: "dvb-latest"
      extras: "easyvdr,channellogos,remotetranscode,cefbrowser"
      extraparameter: "-"
    secrets: inherit
