name: download sources

on:
  workflow_call:
    inputs:
      config:
        description: "CoreELEC or LibreELEC.tv"
        default: CoreELEC-21
        required: true
        type: string

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download sources
        id: download
        run: |
          git submodule update --init -- CoreELEC
          git submodule update --init -- LibreELEC.tv

          if [[ "${{ inputs.config }}" == "CoreELEC-20" ]]; then
              echo "CACHE_NAME=cache-coreelec-20-sources" >> "$GITHUB_OUTPUT"
              echo "CACHE_PATH=CoreELEC/sources" >> "$GITHUB_OUTPUT"
          
              ( cd CoreELEC && git checkout coreelec-20 )
              ./build.sh -config CoreELEC-20-ng -patchonly
          fi

          if [[ "${{ inputs.config }}" == "CoreELEC-21" ]]; then
              echo "CACHE_NAME=cache-coreelec-21-sources" >> "$GITHUB_OUTPUT"
              echo "CACHE_PATH=CoreELEC/sources" >> "$GITHUB_OUTPUT"
          
              ( cd CoreELEC && git checkout coreelec-21 )
              ./build.sh -config CoreELEC-21-ng -patchonly
          fi

          if [[ "${{ inputs.config }}" == "CoreELEC-22" ]]; then
              echo "CACHE_NAME=cache-coreelec-22-sources" >> "$GITHUB_OUTPUT"
              echo "CACHE_PATH=CoreELEC/sources" >> "$GITHUB_OUTPUT"
          
              ( cd CoreELEC && git checkout coreelec-22 )
              ./build.sh -config CoreELEC-22-no -patchonly
          fi

          if [[ "${{ inputs.config }}" == "LibreELEC-11" ]]; then
              echo "CACHE_NAME=cache-libreelec-11-sources" >> "$GITHUB_OUTPUT"
              echo "CACHE_PATH=LibreELEC.tv/sources" >> "$GITHUB_OUTPUT"
          
              ( cd LibreELEC.tv && git checkout libreelec-11.0 )
              ./build.sh -config LibreELEC-11-arm-AMLGX -patchonly
          fi

          if [[ "${{ inputs.config }}" == "LibreELEC-12" ]]; then
              echo "CACHE_NAME=cache-libreelec-12-sources" >> "$GITHUB_OUTPUT"
              echo "CACHE_PATH=LibreELEC.tv/sources" >> "$GITHUB_OUTPUT"
          
              ( cd LibreELEC.tv && git checkout libreelec-12.0 )
              ./build.sh -config LibreELEC-12-aarch64-AMLGX -patchonly
          fi

          if [[ "${{ inputs.config }}" == "LibreELEC-13" ]]; then
              echo "CACHE_NAME=cache-libreelec-13-sources" >> "$GITHUB_OUTPUT"
              echo "CACHE_PATH=LibreELEC.tv/sources" >> "$GITHUB_OUTPUT"
          
              ( cd LibreELEC.tv && git checkout master )
              ./build.sh -config LibreELEC-13-aarch64-AMLGX -patchonly
          fi
  
          if [[ "${{ inputs.config }}" == CoreELEC* ]]; then
            ( cd CoreELEC              
          
              for i in $(tools/viewplan | awk '{ print $2 }' | sed "s/:host//g" | sort -u); do 
                  if [[ "$i" != *:* ]]; then
                      echo "===================================="
                      echo "Download $i"
                      echo "===================================="
                      scripts/get $i
                  else
                      echo "===================================="
                      echo "Prevent Download of $i" 
                      echo "===================================="
                  fi
              done
            )
          
            ls -lR CoreELEC/sources/
          else
            ( cd LibreELEC.tv
          
              for i in $(tools/viewplan | awk '{ print $2 }' | sed "s/:host//g" | sort -u); do 
                  if [[ "$i" != *:* ]]; then
                      echo "===================================="
                      echo "Download $i"
                      echo "===================================="
                      scripts/get $i
                  else
                      echo "===================================="
                      echo "Prevent Download of $i" 
                      echo "===================================="
                  fi
              done
            )
          
            ls -lR LibreELEC.tv/sources/
          fi

      - name: upload sources
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.download.outputs.CACHE_NAME }}
          path: ${{ steps.download.outputs.CACHE_PATH }}
          compression-level: 0
          retention-days: 61
          overwrite: true
          if-no-files-found: ignore