name: Get current git revision
on:
  workflow_dispatch:

jobs:
  build:
    name: Get revision
    runs-on: ubuntu-20.04
    steps:
      - name: Get
        run: |
          set -e
          
          echo "Repository: ${{ github.repository }}"
          
          # Version 1
          CMD="git ls-remote https://github.com/${{ github.repository }} | head -1 | sed \"s/HEAD//\" | cut -c 1-7"
          VREV=eval $CMD || true
          echo "Version 1: $VREV"

          # Version 2
          VREV=`git ls-remote https://github.com/${{ github.repository }} | head -1 | sed "s/HEAD//" | cut -c 1-7`
          echo "Version 2: $VREV"
          
          # Version 3
          VREV=$(git ls-remote https://github.com/${{ github.repository }} | head -1 | sed "s/HEAD//" | cut -c 1-7)
          echo "Version 3: $VREV"