name: Update CoreELEC/LibreELEC

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * 3'

jobs:
  update_ce_le:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout CoreELEC/LibreELEC
        run: |
          git submodule update --init -- CoreELEC
          git submodule update --init -- LibreELEC.tv

      - name: Update CoreELEC/LibreELEC
        run: |
          # Get current version
          ce19_old=$(cat config/versions | grep "COREELEC19=" | awk -F"=" '{ print $2 }')
          ce20_old=$(cat config/versions | grep "COREELEC20=" | awk -F"=" '{ print $2 }')
          ce21_old=$(cat config/versions | grep "COREELEC21=" | awk -F"=" '{ print $2 }')
          le10_old=$(cat config/versions | grep "LIBREELEC10=" | awk -F"=" '{ print $2 }')
          le11_old=$(cat config/versions | grep "LIBREELEC11=" | awk -F"=" '{ print $2 }')
          le12_old=$(cat config/versions | grep "LIBREELEC12=" | awk -F"=" '{ print $2 }')
          le13_old=$(cat config/versions | grep "LIBREELEC13=" | awk -F"=" '{ print $2 }')
          
          # Get latest version
          ce19=$(git ls-remote https://github.com/CoreELEC/CoreELEC.git coreelec-19 | awk '{ print substr($1, 0, 7) }')
          ce20=$(git ls-remote https://github.com/CoreELEC/CoreELEC.git coreelec-20 | awk '{ print substr($1, 0, 7) }')
          ce21=$(git ls-remote https://github.com/CoreELEC/CoreELEC.git coreelec-21 | awk '{ print substr($1, 0, 7) }')
          le10=$(git ls-remote https://github.com/LibreELEC/LibreELEC.tv.git libreelec-10.0 | awk '{ print substr($1, 0, 7) }')
          le11=$(git ls-remote https://github.com/LibreELEC/LibreELEC.tv.git libreelec-11.0 | awk '{ print substr($1, 0, 7) }')
          le12=$(git ls-remote https://github.com/LibreELEC/LibreELEC.tv.git libreelec-12.0 | awk '{ print substr($1, 0, 7) }')
          le13=$(git ls-remote https://github.com/LibreELEC/LibreELEC.tv.git master | awk '{ print substr($1, 0, 7) }')
        
          echo "Update CoreELEC/LibreELEC to version:" > commit.body
          if [ ! "${ce19_old}" = "${ce19}" ]; then 
              echo "  CoreELEC 19 from [${ce19_old}](https://github.com/CoreELEC/CoreELEC/tree/${ce19_old}) to [${ce19}](https://github.com/CoreELEC/CoreELEC/tree/${ce19})" >> commit.body
          fi
          
          if [ ! "${ce20_old}" = "${ce20}" ]; then 
              echo "  CoreELEC 20 from [${ce20_old}](https://github.com/CoreELEC/CoreELEC/tree/${ce20_old}) to [${ce20}](https://github.com/CoreELEC/CoreELEC/tree/${ce20})" >> commit.body
          fi
          
          if [ ! "${ce21_old}" = "${ce21}" ]; then 
              echo "  CoreELEC 21 from [${ce21_old}](https://github.com/CoreELEC/CoreELEC/tree/${ce21_old}) to [${ce21}](https://github.com/CoreELEC/CoreELEC/tree/${ce21})" >> commit.body                    
          fi
          
          if [ ! "${le10_old}" = "${le10}" ]; then 
              echo "  LibreELEC.tv 10 from [${le10_old}](https://github.com/LibreELEC/LibreELEC.tv/tree/${le10_old}) to [${le10}](https://github.com/LibreELEC/LibreELEC.tv/tree/${le10})" >> commit.body          
          fi

          if [ ! "${le11_old}" = "${le11}" ]; then
              echo "  LibreELEC.tv 11 from [${le11_old}](https://github.com/LibreELEC/LibreELEC.tv/tree/${le11_old}) to [${le11}](https://github.com/LibreELEC/LibreELEC.tv/tree/${le11})" >> commit.body
          fi

          if [ ! "${le12_old}" = "${le12}" ]; then
              echo "  LibreELEC.tv 12 from [${le12_old}](https://github.com/LibreELEC/LibreELEC.tv/tree/${le12_old}) to [${le12}](https://github.com/LibreELEC/LibreELEC.tv/tree/${le12})" >> commit.body
          fi

          if [ ! "${le13_old}" = "${le13}" ]; then
              echo "  LibreELEC.tv 13 from [${le13_old}](https://github.com/LibreELEC/LibreELEC.tv/tree/${le13_old}) to [${le13}](https://github.com/LibreELEC/LibreELEC.tv/tree/${le13})" >> commit.body
          fi
      
          # update version
          cat config/versions | sed -e "s/^COREELEC19=.*$/COREELEC19=${ce19}/" \
                              | sed -e "s/^COREELEC20=.*$/COREELEC20=${ce20}/" \
                              | sed -e "s/^COREELEC21=.*$/COREELEC21=${ce21}/" \
                              | sed -e "s/^LIBREELEC10=.*$/LIBREELEC10=${le10}/" \
                              | sed -e "s/^LIBREELEC11=.*$/LIBREELEC11=${le11}/" \
                              | sed -e "s/^LIBREELEC12=.*$/LIBREELEC12=${le12}/" \
                              | sed -e "s/^LIBREELEC13=.*$/LIBREELEC13=${le13}/" > config/versions.new
          
          rm config/versions
          mv config/versions.new config/versions

      - name: Start patch test
        run: |
          ./build.sh -config CoreELEC-19 -extra dynamite,permashift,easyvdr,channellogos,remotetranscode,cefbrowser -patchonly
          ./build.sh -config CoreELEC-20-ng -extra dynamite,permashift,easyvdr,channellogos,remotetranscode,cefbrowser -patchonly
          ./build.sh -config CoreELEC-21-ng -extra dynamite,permashift,easyvdr,channellogos,remotetranscode,cefbrowser -patchonly
          ./build.sh -config CoreELEC-21-ne -extra dynamite,permashift,easyvdr,channellogos,remotetranscode,cefbrowser -patchonly
          ./build.sh -config LibreELEC-11-arm-AMLGX -extra dynamite,permashift,easyvdr,channellogos,remotetranscode,cefbrowser -patchonly
          ./build.sh -config LibreELEC-12-arm-AMLGX -extra dynamite,permashift,easyvdr,channellogos,remotetranscode,cefbrowser -patchonly
          ./build.sh -config LibreELEC-12-x86_64-x11 -extra dynamite,permashift,easyvdr,channellogos,remotetranscode,cefbrowser -patchonly
          ./build.sh -config LibreELEC-13-arm-AMLGX -extra dynamite,permashift,easyvdr,channellogos,remotetranscode,cefbrowser -patchonly
          ./build.sh -config LibreELEC-13-x86_64-x11 -extra dynamite,permashift,easyvdr,channellogos,remotetranscode,cefbrowser -patchonly

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update CoreELEC/LibreELEC.tv
          branch: bot-update-ce-le
          delete-branch: true
          title: '[Bot] Update ce/le'
          body-path: commit.body
          labels: |
            automated pull request
          draft: false