name: Update CoreELEC/LibreELEC

on:
  workflow_dispatch:

jobs:
  update_ce_le:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout CoreELEC/LibreELEC
        run: |
          git submodule update --init -- CoreELEC
          git submodule update --init -- LibreELEC.tv

      - name: Update CoreELEC/LibreELEC
        run: |
          # Get latest version
          ce19=$(git ls-remote https://github.com/CoreELEC/CoreELEC.git coreelec-19 | awk '{ print substr($1, 0, 7) }')
          ce20=$(git ls-remote https://github.com/CoreELEC/CoreELEC.git coreelec-20 | awk '{ print substr($1, 0, 7) }')
          ce21=$(git ls-remote https://github.com/CoreELEC/CoreELEC.git coreelec-21 | awk '{ print substr($1, 0, 7) }')
          le10=$(git ls-remote https://github.com/LibreELEC/LibreELEC.tv.git libreelec-10.0 | awk '{ print substr($1, 0, 7) }')
          le11=$(git ls-remote https://github.com/LibreELEC/LibreELEC.tv.git libreelec-11.0 | awk '{ print substr($1, 0, 7) }')
          le12=$(git ls-remote https://github.com/LibreELEC/LibreELEC.tv.git master | awk '{ print substr($1, 0, 7) }')
      
          echo "Update CoreELEC/LibreELEC to version:" > commit.body
          echo "  CoreELEC 19 to ${ce19}" >> commit.body
          echo "  CoreELEC 20 to ${ce20}" >> commit.body
          echo "  CoreELEC 21 to ${ce21}" >> commit.body
          echo "  LibreELEC.tv 10 to ${le10}" >> commit.body
          echo "  LibreELEC.tv 11 to ${le11}" >> commit.body
          echo "  LibreELEC.tv 12 to ${le12}" >> commit.body
      
          # update version
          cat config/versions | sed -e "s/^COREELEC19=.*$/COREELEC19=${ce19}/" \
                              | sed -e "s/^COREELEC20=.*$/COREELEC20=${ce20}/" \
                              | sed -e "s/^COREELEC21=.*$/COREELEC21=${ce21}/" \
                              | sed -e "s/^LIBREELEC10=.*$/LIBREELEC10=${le10}/" \
                              | sed -e "s/^LIBREELEC11=.*$/LIBREELEC11=${le11}/" \
                              | sed -e "s/^LIBREELEC12=.*$/LIBREELEC12=${le12}/" > config/versions.new
          
          rm config/versions
          mv config/versions.new config/versions

      - name: Start patch test
        run: |
          ./build.sh -config CoreELEC-19 -extra dynamite,permashift,easyvdr,channellogos,remotetranscode,cefbrowser -patchonly
          ./build.sh -config CoreELEC-20-ng -extra dynamite,permashift,easyvdr,channellogos,remotetranscode,cefbrowser -patchonly
          ./build.sh -config CoreELEC-21-ng -extra dynamite,permashift,easyvdr,channellogos,remotetranscode,cefbrowser -patchonly
          ./build.sh -config CoreELEC-21-ne -extra dynamite,permashift,easyvdr,channellogos,remotetranscode,cefbrowser -patchonly
          ./build.sh -config LibreELEC-11-arm-AMLGX -extra dynamite,permashift,easyvdr,channellogos,remotetranscode,cefbrowser -patchonly
          ./build.sh -config LibreELEC-master-arm-AMLGX -extra dynamite,permashift,easyvdr,channellogos,remotetranscode,cefbrowser -patchonly
          ./build.sh -config LibreELEC-master-x86_64-x11 -extra dynamite,permashift,easyvdr,channellogos,remotetranscode,cefbrowser -patchonly

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update CoreELEC/LibreELEC.tv
          branch: bot-update-ce-le
          delete-branch: true
          title: '[Bot] Update ce/le'
          body-path: commit.body
          labels: |
            automated pull request
          draft: false